"""
Scoring Models - Data classes for multi-dimensional composite scoring.
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from enum import Enum


class ConfidenceLevel(str, Enum):
    """Confidence level classification for composite scores."""
    VERY_HIGH = "very_high"    # 85-100
    HIGH = "high"              # 70-84
    MODERATE = "moderate"      # 50-69
    LOW = "low"                # 30-49
    VERY_LOW = "very_low"      # 0-29

    @classmethod
    def from_score(cls, score: float) -> "ConfidenceLevel":
        """Convert numeric score to confidence level."""
        if score >= 85:
            return cls.VERY_HIGH
        elif score >= 70:
            return cls.HIGH
        elif score >= 50:
            return cls.MODERATE
        elif score >= 30:
            return cls.LOW
        return cls.VERY_LOW


class InsightCategory(str, Enum):
    """Categories for insights generated by the scorer."""
    STRENGTH = "strength"
    RISK = "risk"
    OPPORTUNITY = "opportunity"
    RECOMMENDATION = "recommendation"


class CompetitorInfoDisplay(BaseModel):
    """Individual competitor information for frontend display."""
    company: str = Field(..., description="Company name")
    drug: str = Field(..., description="Drug name")
    phase: str = Field(..., description="Development phase (Phase 1, Phase 2, Phase 3, Approved)")


class SubScore(BaseModel):
    """Individual dimension score with breakdown."""
    dimension: str = Field(..., description="Dimension name (scientific_evidence, market_opportunity, etc.)")
    score: float = Field(..., ge=0, le=100, description="Score for this dimension (0-100)")
    weight: float = Field(..., ge=0, le=1, description="Weight of this dimension (0-1)")
    weighted_score: float = Field(..., description="Score multiplied by weight")
    confidence: ConfidenceLevel = Field(..., description="Confidence level for this dimension")
    factors: Dict[str, Any] = Field(default_factory=dict, description="Individual factor scores and raw values")
    data_completeness: float = Field(default=1.0, ge=0, le=1, description="How much data was available (0-1)")
    notes: List[str] = Field(default_factory=list, description="Explanation of scoring")
    # Competitor list for competitive_landscape dimension (populated only for that dimension)
    competitors: List[CompetitorInfoDisplay] = Field(default_factory=list, description="List of competitors (for competitive_landscape dimension)")


class Insight(BaseModel):
    """A single insight or recommendation."""
    category: InsightCategory = Field(..., description="Type of insight")
    title: str = Field(..., description="Short title for the insight")
    description: str = Field(..., description="Detailed description")
    severity: str = Field(..., description="Severity level: high, medium, low")
    source_dimension: str = Field(..., description="Which dimension generated this insight")
    supporting_data: Optional[Dict[str, Any]] = Field(default=None, description="Data supporting this insight")


class CompositeScore(BaseModel):
    """Multi-dimensional composite score for a repurposing opportunity."""
    indication: str = Field(..., description="Disease/indication name")
    overall_score: float = Field(..., ge=0, le=100, description="Weighted composite score (0-100)")
    confidence_level: ConfidenceLevel = Field(..., description="Overall confidence level")

    # Sub-scores by dimension
    scientific_evidence: SubScore = Field(..., description="Scientific evidence score")
    market_opportunity: SubScore = Field(..., description="Market opportunity score")
    competitive_landscape: SubScore = Field(..., description="Competitive landscape score")
    development_feasibility: SubScore = Field(..., description="Development feasibility score")

    # Insights and recommendations
    key_strengths: List[Insight] = Field(default_factory=list, description="Key strengths identified")
    key_risks: List[Insight] = Field(default_factory=list, description="Key risks identified")
    recommended_next_steps: List[Insight] = Field(default_factory=list, description="Recommended actions")

    # Metadata
    evidence_count: int = Field(..., description="Total evidence items")
    data_completeness: float = Field(default=1.0, ge=0, le=1, description="Overall data availability")
    scored_at: Optional[str] = Field(default=None, description="ISO timestamp of scoring")


class EnhancedIndicationResult(BaseModel):
    """Enhanced indication result with composite scoring."""
    indication: str = Field(..., description="Disease/indication name")
    confidence_score: float = Field(..., ge=0, le=100, description="Overall composite score (backward compatible)")
    composite_score: CompositeScore = Field(..., description="Full composite score breakdown")
    evidence_count: int = Field(..., description="Number of supporting evidence items")
    supporting_sources: List[str] = Field(..., description="List of data sources")

    class Config:
        json_schema_extra = {
            "example": {
                "indication": "Type 2 Diabetes",
                "confidence_score": 78.5,
                "evidence_count": 15,
                "supporting_sources": ["clinical_trials", "literature", "opentargets"]
            }
        }


class MarketData(BaseModel):
    """Market data for scoring market opportunity dimension."""
    indication: str = Field(..., description="Indication name")
    market_size_usd_billions: Optional[float] = Field(default=None)
    cagr_percent: Optional[float] = Field(default=None)
    unmet_need_score: Optional[float] = Field(default=None, ge=0, le=100)
    patient_population_millions: Optional[float] = Field(default=None)
    pricing_potential: Optional[str] = Field(default=None, description="premium, standard, generic")


class CompetitorData(BaseModel):
    """Competitive landscape data for scoring."""
    indication: str = Field(..., description="Indication name")
    total_competitors: int = Field(default=0)
    approved_drugs_count: int = Field(default=0)
    phase3_trials_count: int = Field(default=0)
    phase2_trials_count: int = Field(default=0)
    phase1_trials_count: int = Field(default=0)
    big_pharma_involved: bool = Field(default=False)
    # Actual competitor details for display
    competitor_list: List[CompetitorInfoDisplay] = Field(default_factory=list, description="List of competitor details")


class PatentData(BaseModel):
    """Patent and regulatory data for development feasibility scoring."""
    indication: str = Field(..., description="Indication name")
    has_existing_safety_data: bool = Field(default=False)
    years_of_safety_data: int = Field(default=0)
    regulatory_pathway: str = Field(default="standard", description="accelerated, standard, complex")
    orphan_drug_potential: bool = Field(default=False)
    patent_status: str = Field(default="unknown", description="active, expiring, expired, novel")
    exclusivity_remaining_years: Optional[float] = Field(default=None)


# =============================================================================
# ENHANCED COMPARATIVE ANALYSIS MODELS
# =============================================================================

class ComparatorDrug(BaseModel):
    """Information about an existing treatment (standard of care)."""
    drug_name: str = Field(..., description="Name of the comparator drug")
    drug_id: Optional[str] = Field(default=None, description="ChEMBL ID or DrugBank ID")
    mechanism: str = Field(default="Unknown", description="Mechanism of action")
    administration_route: str = Field(default="oral", description="oral, IV, subcutaneous, topical, etc.")
    dosing_frequency: str = Field(default="daily", description="daily, twice daily, weekly, monthly, etc.")
    typical_duration: Optional[str] = Field(default=None, description="Treatment duration")
    age_restrictions: Optional[str] = Field(default=None, description="Age group limitations e.g., '18-65 years'")
    key_side_effects: List[str] = Field(default_factory=list, description="Common side effects")
    contraindications: List[str] = Field(default_factory=list, description="Key contraindications")
    average_monthly_cost: Optional[float] = Field(default=None, description="Average monthly treatment cost in USD")
    approval_year: Optional[int] = Field(default=None, description="Year of FDA approval")
    market_share_percent: Optional[float] = Field(default=None, description="Estimated market share")


class ComparativeAdvantage(BaseModel):
    """A specific advantage of the candidate drug over existing treatments."""
    category: str = Field(..., description="Category: dosing, administration, safety, efficacy, access, convenience")
    advantage_type: str = Field(..., description="Short type label e.g., 'Oral vs Injectable'")
    description: str = Field(..., description="Detailed description of the advantage")
    comparator_drug: str = Field(..., description="Name of the drug being compared against")
    comparator_value: str = Field(..., description="The comparator's characteristic e.g., 'IV infusion weekly'")
    candidate_value: str = Field(..., description="The candidate's characteristic e.g., 'Oral tablet daily'")
    impact: str = Field(default="medium", description="Impact level: high, medium, low")
    patient_benefit: Optional[str] = Field(default=None, description="Direct patient benefit description")


class SideEffectEntry(BaseModel):
    """Individual side effect with frequency data."""
    effect_name: str = Field(..., description="Name of the side effect")
    frequency_percent: Optional[float] = Field(default=None, description="Frequency as percentage (0-100)")
    severity: str = Field(default="moderate", description="Severity: mild, moderate, severe")
    category: str = Field(default="general", description="Category: GI, CNS, cardiovascular, etc.")


class SideEffectComparison(BaseModel):
    """Comparison of side effect profiles between candidate and comparator drugs."""
    indication: str = Field(..., description="Indication being compared for")
    candidate_drug: str = Field(..., description="The candidate drug name")
    comparator_drug: str = Field(..., description="The comparator drug name")
    eliminated_effects: List[SideEffectEntry] = Field(
        default_factory=list,
        description="Side effects present in comparator but not in candidate"
    )
    reduced_effects: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Side effects with lower frequency in candidate. Dict has: effect_name, comparator_freq, candidate_freq"
    )
    new_concerns: List[SideEffectEntry] = Field(
        default_factory=list,
        description="Side effects unique to the candidate drug"
    )
    shared_effects: List[str] = Field(
        default_factory=list,
        description="Side effects common to both drugs"
    )
    safety_advantage_score: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Overall safety advantage (-1 = worse, 0 = similar, 1 = better)"
    )
    safety_summary: Optional[str] = Field(default=None, description="Text summary of safety comparison")


class MarketSegment(BaseModel):
    """Specific market segment within a broader indication."""
    segment_name: str = Field(..., description="Specific segment name e.g., 'Second-line NSCLC therapy'")
    parent_indication: str = Field(..., description="Parent indication e.g., 'Lung Cancer'")
    segment_size_billions: Optional[float] = Field(default=None, description="Segment market size in USD billions")
    total_indication_size_billions: Optional[float] = Field(default=None, description="Total indication market size")
    segment_share_percent: Optional[float] = Field(default=None, description="Segment's share of total market")
    patient_subpopulation: Optional[int] = Field(default=None, description="Number of patients in this segment")
    total_indication_population: Optional[int] = Field(default=None, description="Total indication patient population")
    unmet_need_level: str = Field(default="moderate", description="very_high, high, moderate, low")
    unmet_need_description: Optional[str] = Field(default=None, description="Description of unmet need")
    target_patient_profile: Optional[str] = Field(
        default=None,
        description="Description of target patient e.g., 'Adults 18-75 with EGFR+ NSCLC who failed first-line therapy'"
    )
    key_differentiators: List[str] = Field(
        default_factory=list,
        description="What differentiates this segment opportunity"
    )
    growth_rate_percent: Optional[float] = Field(default=None, description="Segment CAGR")
    competitive_intensity: str = Field(default="medium", description="high, medium, low")


class KeyPublication(BaseModel):
    """A key scientific publication supporting the opportunity."""
    pmid: Optional[str] = Field(default=None, description="PubMed ID")
    title: str = Field(..., description="Publication title")
    authors: Optional[str] = Field(default=None, description="First author et al.")
    journal: Optional[str] = Field(default=None, description="Journal name")
    year: Optional[int] = Field(default=None, description="Publication year")
    key_finding: str = Field(..., description="Key finding relevant to repurposing")
    citation_count: Optional[int] = Field(default=None, description="Number of citations")
    url: Optional[str] = Field(default=None, description="URL to publication")


class ScientificDetails(BaseModel):
    """Detailed scientific data for researchers."""
    drug_name: str = Field(..., description="Drug being analyzed")
    indication: str = Field(..., description="Target indication")
    mechanism_of_action: str = Field(default="Unknown", description="Detailed mechanism of action")
    target_protein: Optional[str] = Field(default=None, description="Primary protein target name")
    target_gene: Optional[str] = Field(default=None, description="Target gene symbol")
    target_class: Optional[str] = Field(default=None, description="Target class e.g., 'Kinase', 'GPCR'")
    pathways: List[str] = Field(default_factory=list, description="Involved biological pathways")
    binding_affinity_nm: Optional[float] = Field(default=None, description="Binding affinity in nanomolar")
    selectivity_profile: Optional[str] = Field(default=None, description="Selectivity vs related targets")
    key_publications: List[KeyPublication] = Field(default_factory=list, description="Key supporting publications")
    preclinical_models: List[str] = Field(default_factory=list, description="Relevant preclinical models tested")
    biomarkers: List[str] = Field(default_factory=list, description="Relevant biomarkers")
    clinical_evidence_summary: Optional[str] = Field(default=None, description="Summary of clinical evidence")
    mechanistic_rationale: Optional[str] = Field(
        default=None,
        description="Why this drug should work for this indication based on mechanism"
    )


class EnhancedOpportunityData(BaseModel):
    """Complete enhanced data for a repurposing opportunity including comparisons."""
    indication: str = Field(..., description="Target indication")
    composite_score: Optional[CompositeScore] = Field(default=None, description="Full composite score")

    # Comparative Analysis
    comparator_drugs: List[ComparatorDrug] = Field(
        default_factory=list,
        description="Current standard of care treatments"
    )
    comparative_advantages: List[ComparativeAdvantage] = Field(
        default_factory=list,
        description="Specific advantages over existing treatments"
    )
    side_effect_comparison: Optional[SideEffectComparison] = Field(
        default=None,
        description="Safety profile comparison"
    )

    # Market Segmentation
    market_segment: Optional[MarketSegment] = Field(
        default=None,
        description="Target market segment details"
    )

    # Scientific Details
    scientific_details: Optional[ScientificDetails] = Field(
        default=None,
        description="Detailed scientific data"
    )

    # Summary
    key_benefits_summary: List[str] = Field(
        default_factory=list,
        description="Top-line benefits over existing treatments"
    )
    positioning_statement: Optional[str] = Field(
        default=None,
        description="Strategic positioning statement"
    )
